### ISSUE TITLE
Can't find my service

### ISSUE THREAD

**Issue by cabralfortiss** [arrowhead-f/core-java#15]
I registered my own service, I can see it on the database and can also remove it, but when I query about it, I get an empty response:

`New POST request at: http://127.0.0.1:80/serviceregistry/register
{
  "providedService" : {
    "serviceDefinition" : "myService",
    "interfaces" : [ "JSON" ],
    "serviceMetadata" : { }
  },
  "provider" : {
    "systemName" : "MySystemName",
    "address" : "127.0.0.5",
    "port" : 8089
  },
  "port" : 8090,
  "serviceURI" : "MYServiceURI",
  "version" : 1,
  "udp" : false,
  "ttl" : 5
}

Response to the request at: http://127.0.0.1:80/serviceregistry/register
{
  "id" : 28,
  "providedService" : {
    "serviceDefinition" : "myService",
    "interfaces" : [ "JSON" ]
  },
  "provider" : {
    "id" : 27,
    "systemName" : "MySystemName",
    "address" : "127.0.0.5",
    "port" : 8089
  },
  "serviceUri" : "MYServiceURI",
  "udp" : false,
  "version" : 1
}

-------------

New PUT request at: http://127.0.0.1:80/serviceregistry/query
{
  "service" : {
    "serviceDefinition" : "myService",
    "interfaces" : [ "JSON" ],
    "serviceMetadata" : { }
  },
  "metadataSearch" : false,
  "pingProviders" : true,
  "version" : 1
}

Response to the request at: http://127.0.0.1:80/serviceregistry/query
{
  "serviceQueryData" : [ ]
}
`

but querying InsecureOrchestrationService works fine. Is there some typo that I cannot see or what am I doing wrong?

**Comment by uzoltan** [comment]
Does your provider listen at 127.0.0.5:8090? Because the ServiceRegistry thinks it listens on 127.0.0.5:8089, and I assume when it tries to ping it (because pingProviders is true in the query payload), it will not get a response, and the provider will be filtered from the response list. The payload changed slightly since the 4.0 release, and the port is now inside the arrowhead system class.

I could write a long paragraph about why exactly the ServiceRegistryEntry payload looks like as it is right now (https://github.com/arrowhead-f/core-java/blob/develop/common/src/main/java/eu/arrowhead/common/database/ServiceRegistryEntry.java), if you're interested. But the short answer is, that if you send this, up-to-date registering payload (when using the develop branch):
 
{
"providedService" : {
"serviceDefinition" : "myService",
"interfaces" : [ "JSON" ]
},
"provider" : {
"systemName" : "MySystemName",
"address" : "127.0.0.5",
"port" : 8090
},
"serviceURI" : "MYServiceURI",
"endOfValidity" : "2018-10-16 15:00:00"
}

then I think your query will be successful.

**Comment by uzoltan** [comment]
I don't have the resources to keep all available documentation up to date, but recently I added swagger UI (https://swagger.io/tools/swagger-ui/) to each core system.

If you go to http://127.0.0.1:80/api/ you will get a basic description of the service registry API with all of its available endpoints. If you open an endpoint, it even shows example, full request bodies (meaning it contains all the fields, not just the mandatory ones).

**Comment by cabralfortiss** [comment]
Thanks for the help. The problem was indeed the non-listening port (inside the system). I kept the other port (a wrong one) and I still could query. Some hint: I have to use 0.0.0.0 as address, since it didn't work with 127.0.0.1.

Regarding the register message, I assume that the extra port should be deleted from https://github.com/arrowhead-f/core-java/blob/master/documentation/ServiceRegistry/Arrowhead%20ServiceDiscovery%20Service%20G4.0%20SD.docx? what about the ttl field?

**Comment by uzoltan** [comment]
Yes, as I said, the manually created documentations are still on the 4.0 release version (in the master branch too, which is almost identical to the release/4.0 branch). 

The TTL field was a "leftover" from the DNS-SD version of the SR, it stands for Time To Live, and it contained  the time in seconds, until the given service should be considered valid/active. At some point, the idea was that both versions of the SR would have the same exact interface, but the DNS-SD version had a few heavy requirements, and its hard to use.
I replaced this TTL field with the more descriptive endOfValidity, which is of type LocalDateTime.

The address problem: I guess this depends on the app.conf of your provider. If the "address" field in the app.conf is 0.0.0.0, then it will bind to every available ethernet interface (127.0.X.X, localhost, 0.0.0.0, local IP). If the address is on the local IP, then only local IP will work, same with the loopback interface. I'm not sure if I understand where did you had to change the address though.

**Comment by uzoltan** [comment]
For testing/prototyping, you can send actual requests directly from the swagger UI, or using a REST client with a nice UI like Postman.
