### ISSUE TITLE
Issue with newer Java versions

### ISSUE THREAD

**Issue by eudyptula** [arrowhead-f/core-java#18]
Java 10 (as used by the Debian packages) is no longer available in the reposityory, see https://launchpad.net/~linuxuprising/+archive/ubuntu/java

The '--add-modules java.xml.bind' temporary hack is not longer available in Java 11. So we need to probably update the maven dependencies to include it instead...

**Comment by eudyptula** [comment]
Nah, keep running into the same "com.sun.xml.bind.v2.ContextFactory not found" exception, no matter what dependencies I add! Any ideas?

**Comment by uzoltan** [comment]
1) Isn't there another repository where JDK 10 is available? And apt could be configured to search for the JDK there. 

2) I think there are a lot more dependency changes that are needed for Java 11. I'm making this assumption based on this migration guide: https://blog.codefx.org/java/java-11-migration-guide/

3) Another option would be to just use Java 8 for now. In the main README we also state JDK 8 as a requirement. The code is written in that, and it does not take advantage of any of the new jdk 9+ features yet. Sadly since JavaEE is no more, backwards compatibility is broken without "hacks". Big libraries/frameworks still work on jdk 11 and module system support, so I dont think we need to rush it ourselves.

(Btw I'm on a holiday leave on next week)

**Comment by eudyptula** [comment]
1. Don't seem so, recall they reference a Oracle reason for that.

2. Thanks, your link inspired me: See pull-request #19

3. Yea, it's all a mess. Originally thought Java 10/11 would maintain backward compatibility. Good thing Java 8 repository is still up (https://launchpad.net/~webupd8team/+archive/ubuntu/java) Maybe we should reference this in the guide also?

**Comment by uzoltan** [comment]
> Maybe we should reference this in the guide also?

Yeah I think that's a good idea.

**Comment by eudyptula** [comment]
I included it within my code, so it will eventually make it to the main repository.

**Comment by uzoltan** [comment]
I lightly tested the PR on Windows, using both JDK 8 and 11, the orchestration was successful, so I merged it. f652b3c63da61ccb9cd2215d9ef0f258176f581b
