### ISSUE TITLE
Consumer registration

### ISSUE THREAD

**Issue by eudyptula** [arrowhead-f/core-java#24]
Could we allow consumers to enter the arrowhead_system DB table by themselves?

For example, this could possibly be done by allowing service = null when registering in the service registry system. Or maybe this will be handled by the system registry in the future?

**Comment by uzoltan** [comment]
What do you mean by this exactly? Do you mean the whole arrowhead_system table, or just the entry for the consumer system, or what exactly, I'm not sure.

**Comment by eudyptula** [comment]
Just the entry for the consumer system inside the arrowhead_system table. The provider skeleton creates this entry itself during service registration - the consumer skeleton does not.

**Comment by uzoltan** [comment]
Since the consumer skeleton is not running a webserver - it only runs until the orchestration request finishes of fails - it should not talk to the SR because of this. There is this API class: https://github.com/arrowhead-f/core-java/blob/develop/common/src/main/java/eu/arrowhead/common/web/ArrowheadSystemApi.java

which is also available through the Orchestrator. But right now I dont see a lot of point to the consumer registering its arrowhead_system entry into the database. 

If you raised this issue in terms of bootstrapping, meaning how can we avoid the need for adding manual authorization right to the database, then I don't have a truly good solution for that. Right now, the provider can be configured with the -auth command line argument, to also do an intra-cloud authorization registering, but beyond the quickstart scenario, we can not assume that providers will know their consumers in advance.

**Comment by eudyptula** [comment]
Was still going to add the intra-cloud entry manually - it would just be much easier to add, when the entry in the arrowhead_system is already present. Only need to refer to the ids and not having to enter system_name, host, base64 key, etc.

It could also help in the admin GUI when creating the intra-cloud entry. Here the consumer can be selected in a list of known systems, which is user can use to select which systems to allow to interact.

But yea, see your point that it may be out of the scope for the service registry - maybe I'm just being too lazy... Also, spawns the question of when/how to remove them again...

**Comment by uzoltan** [comment]
The issues you mentioned are valid, in this state this is not scalable. Csaba is kinda working on trying to figure out a good bootstrapping procedure, starting from the device level, but this is still in early stages, and the requirements are not well known.

**Comment by eudyptula** [comment]
I usually start mine, let them fail the first time, then go in add the entry, and retry.
But looking forward to hear/see more of Csaba' work on bootstrapping...
