### ISSUE TITLE
Problem with orchestrator not finding the rule

### ISSUE THREAD

**Issue by cabralfortiss** [arrowhead-f/core-java#36]
I tried to store a rule and then ask for it, but I got an error from the orchestrator. I put below the logging information: 

I stored a rule:

```
New POST request at: http://127.0.0.1:8440/orchestrator/mgmt/store
[ {
  "service" : {
    "serviceDefinition" : "emergencyLight",
    "interfaces" : [ ],
    "serviceMetadata" : { }
  },
  "consumer" : {
    "systemName" : "Button",
    "address" : "127.0.0.1",
    "port" : 80,
    "authenticationInfo" : ""
  },
  "providerSystem" : {
    "systemName" : "DEPOSIT1",
    "address" : "127.0.0.1",
    "port" : 80,
    "authenticationInfo" : ""
  },
  "priority" : 1,
  "defaultEntry" : true,
  "name" : "",
  "lastUpdated" : "",
  "instruction" : "",
  "attributes" : { },
  "serviceURI" : "emergencyLight"
} ]
```

And it returns OK:

```
Response to the request at: http://127.0.0.1:8440/orchestrator/mgmt/store
[ {
  "id" : 25,
  "service" : {
    "id" : 21,
    "serviceDefinition" : "emergencyLight",
    "interfaces" : [ ]
  },
  "consumer" : {
    "id" : 24,
    "systemName" : "Button",
    "address" : "127.0.0.1",
    "port" : 80,
    "authenticationInfo" : ""
  },
  "providerSystem" : {
    "id" : 22,
    "systemName" : "DEPOSIT1",
    "address" : "127.0.0.1",
    "port" : 80,
    "authenticationInfo" : ""
  },
  "priority" : 1,
  "defaultEntry" : true,
  "name" : "",
  "lastUpdated" : "2018-11-13T14:43:10.175",
  "instruction" : ""
} ]
```
And when I tried to retrieve the rule:

```
New POST request at: http://127.0.0.1:80/orchestrator/orchestration
{
  "requesterSystem" : {
    "systemName" : "Button",
    "address" : "127.0.0.1",
    "port" : 80,
    "authenticationInfo" : ""
  },
  "requestedService" : {
    "serviceDefinition" : "emergencyLight",
    "interfaces" : [ ],
    "serviceMetadata" : { }
  },
  "orchestrationFlags" : { },
  "preferredProviders" : [ ],
  "requestedQoS" : { }
}
```
I got:

```
eu.arrowhead.common.exception.DataNotFoundException: OrchestrationFromStore failed with all the queried (1) Store entries.
	at eu.arrowhead.core.orchestrator.OrchestratorService.orchestrationFromStore(OrchestratorService.java:209)
	at eu.arrowhead.core.orchestrator.OrchestratorResource.orchestrationProcess(OrchestratorResource.java:65)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Unknown Source)
Response to the request at: http://127.0.0.1:80/orchestrator/orchestration
{
  "errorMessage" : "OrchestrationFromStore failed with all the queried (1) Store entries.",
  "errorCode" : 404,
  "exceptionType" : "DATA_NOT_FOUND",
  "origin" : "http://127.0.0.1:80/orchestrator/orchestration",
  "documentation" : "https://github.com/arrowhead-f/core-java/tree/master/documentation"
}
```
What am I doing wrong here?

**Comment by uzoltan** [comment]
I think this can only happen with this (intra-cloud) payload if at line 159 of OrchestratorService
`entryList = OrchestratorDriver.crossCheckStoreEntries(srf, entryList);`

returns 0 remaining entries, thus the for loop at line 175 will iterate 0 times, and the exception at line 208 will be thrown.

Quoting the javadoc of the `crossCheckStoreEntries `method:
Cross-checks the query results from the <i>Orchestration Store</i> with the <i>Service Registry</i> and <i>Authorization</i>. A provider <tt>ArrowheadSystem</tt> has to be registered into the <i>Service Registry</i> at the time of the servicing request while being authorized too.

So a provider from an Orchestration Store rule still has to be registered into the SR and Auth in order to be returned by the orchestration service. If you have the logging setup with a high enough log level (either file or database), you should see (I think) a log message like this:
"crossCheckStoreEntries returns 0 orchestration store entries"

**Comment by cabralfortiss** [comment]
mmmm the provider is registered in the SR and I can reach it. However I don't do anything yet with the Authorization. What should I do with it?
From the log I can see the following logs one right after the other (both comming from eu.arrowhead.core.orchestrator.OrchestratorDriver):
queryOrchestrationStore returns 1 orchestration store entries matching the criteria
crossCheckStoreEntries catches DataNotFoundException from SR/Auth query

**Comment by uzoltan** [comment]
That must be the exception thrown by the queryAuthorization method then (inside crossCheckStoreEntries). 

As an "arrowhead local cloud operator" you have 2 options adding the needed authorization rule:

- Use the REST interface of the Authorization (this is a management interface, which in secure mode can only be accessed with the right certificate)
Based on your orchestration entry, this would look like this:
POST @ http://localhost:8444/authorization/mgmt/intracloud
payload:
```
{
	"consumer": {
		"systemName" : "Button",
                "address" : "127.0.0.1",
                "port" : 80
	},
	"providerList": [{
			"systemName" : "DEPOSIT1",
                        "address" : "127.0.0.1",
                        "port" : 80
		}
	],
	"serviceList": [{
			"serviceDefinition" : "emergencyLight"
		}
	]
}
```

- Insert a new entry into the intra_cloud_authorization table manually. It has 4 columns (id, consumer_system_id, provider_system_id, arrowhead_service_id). In your case this could be the following:  654 (any unique id number inside this table would do for ID), 24, 22, 21

And a side note: for the core systems, you do not need to send empty fields and arrays.
(for example:
```
"orchestrationFlags" : { },
  "preferredProviders" : [ ],
  "requestedQoS" : { }
``` )
The JSON library is configured to ignore the empty arrays, although fields can be different. I think "" will map to an empty string instead of null. It doesn't make a difference here, I just thought I would mention.

**Comment by cabralfortiss** [comment]
I added the authortization rule and I can see it in the databank. But the problem persists. I get the same error. 

Regarding the empty fields, I generate the JSON from the datastructure holding the payload, so it's easier for me not to check that, at least for now in testing mode

**Comment by cabralfortiss** [comment]
In a deeper look, I think is not the same problem, but the same result. So the logger shows:

```
eu.arrowhead.core.orchestrator.OrchestratorResource				INFO	Received an orchestrationFromStore request.
eu.arrowhead.core.orchestrator.OrchestratorDriver				INFO	queryOrchestrationStore returns 1 orchestration store entries matching the criteria
eu.arrowhead.common.Utility	 									INFO	Sending PUT request to: http://127.0.0.1:8442/serviceregistry/query
eu.arrowhead.core.serviceregistry_sql.ServiceRegistryResource	INFO	Service ArrowheadService{serviceDefinition=emergencyLight} queried successfully.
eu.arrowhead.core.orchestrator.OrchestratorDriver				INFO	queryServiceRegistry was successful, number of potential providers forArrowheadService{serviceDefinition=emergencyLight} is 1
eu.arrowhead.common.Utility										INFO	Sending PUT request to: http://127.0.0.1:8444/authorization/intracloud
eu.arrowhead.core.authorization.AuthorizationResource			INFO	IntraCloud auth check for consumer Button returns with 1 possible provider
eu.arrowhead.core.orchestrator.OrchestratorDriver				INFO	queryAuthorization is done, sending back 1 authorized Systems
eu.arrowhead.core.orchestrator.OrchestratorDriver				INFO	crossCheckStoreEntries returns 0 orchestration store entries
eu.arrowhead.core.orchestrator.OrchestratorService				ERROR	orchestrationFromStore throws final DataNotFoundException


```

**Comment by uzoltan** [comment]
Can you send me an export of your database via email? I want to see if I can reproduce this on my machine.

**Comment by uzoltan** [comment]
Thanks, I found the problem and working on it now.

**Comment by uzoltan** [comment]
This was a cool bug to hunt down, I finally found the root reason of it, it has to do with the "authenticationInfo" : "" part.

**Comment by uzoltan** [comment]
I'm pretty sure 6a2fa781d823514b843436699e30c8cb5cc02411 fixed the issue.

The problem in detail: 
The get intra cloud auth rights interface of the Authorization returns an object ([IntraCloudAuthResponse ](https://github.com/arrowhead-f/core-java/blob/develop/common/src/main/java/eu/arrowhead/common/messages/IntraCloudAuthResponse.java))with a hashmap inside, where the key is a complex object, namely an ArrowheadSystem. 
The Jackson JSON library does not handle a complex object for a hashmap key out of the box well. For serialization it uses the object's toString method (this is why the ArrowheadSystem has a different toString() method from the other database classes), and there is a [custom KeyDeserializer class](https://github.com/arrowhead-f/core-java/blob/develop/common/src/main/java/eu/arrowhead/common/json/ArrowheadSystemKeyDeserializer.java) defined for the deserialization. This class uses the ArrowheadSystem(String) constructor to deserialize the ArrowheadSystem back to an object. 

So far that constructor worked well so far, because I never tested it for a case where the authenticationInfo is an empty string :) System name, address and port can not be null thanks to the constraints on them, but auth info can. So when authInfo is `null`, it gets deserialized into a string as "null". But when it is an empty string, it will not be seen in the serialized string at all.

So the Authorization instead of sending back:
`{
  "authorizationState" : {
    "DEPOSIT1,127.0.0.1,80,null" : true
  }
}`

it will send back:
`{
  "authorizationState" : {
    "DEPOSIT1,127.0.0.1,80," : true
  }
}`

And this custom deserialization method in the ArrowheadSystem class was not prepared for it, the ArrowheadSystem got deserialized into an object where the systemName was "DEPOSIT1", but all the other fields were `null`. That tripped the equals method called by the `!providerSystemsFromAuth.contains(entry.getProviderSystem())` command at line 305 of the OrchestratorDriver.

**Comment by cabralfortiss** [comment]
wow! thanks! tested and working like a charm.
