### ISSUE TITLE
URL path of core services not according to the documentation

### ISSUE THREAD

**Issue by cabralfortiss** [arrowhead-f/core-java#41]
Specifically in the Service Registry, according to the documentation the URL subpath for the services are "/register", "/remove" and "/query" but in the implementation they all have a "/serviceregistry" prefix, that is: "/serviceregistry/register", "/serviceregistry/remove" and "/serviceregistry/query".

I didn't find any information where this extra prefix comes from. This causes some troubles since implementing an API has to be changed to fit this address

**Comment by hegeduscs** [comment]
The /serviceregistry part comes from the identification of the core system that you are talking to. It is possible that you are hosting all core systems under the same port (i.e. lightweight implementation).  It is also possible that the system is providing more than one services. 

This is a documentation issue, needs to be indicated clearly. I think it should be present in the SysD.

**Comment by hegeduscs** [comment]
The concept is that a full URL comes together from two parts: /serviceURL/methodURL, where the methodURLs are described in the IDD, belonging to the service interface contract. 

Meanwhile, the serviceURL is provider instance specific, and is stored in the ServiceRegistryEntry. 

This logic applies to the SR as well, and we implemented the serviceURL as /serviceregistry. In this case, this URL is also not mandatory, can be SR instance specific. However, the providers have to know this in advance in order to connect to that SR instance. 

We have no established guideline on this issue, nor for other protocols.

**Comment by cabralfortiss** [comment]
Thanks for the clarification, now is much clearer. I'd recommend to have a "documentationBug" label to differentiate them from code bugs

**Comment by uzoltan** [comment]
in e08913ef19ee0b9883444e5241473eedea5850b6 I updated the IDD docs with a baseURL sentence.
